version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      # - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:80"
    depends_on:
      - nginx
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - DB_HOST=mongo
      - DB_NAME=users
      - DB_PORT=27017
    depends_on:
      - nginx
      - mongo
    restart: always


  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
